### ISSUE TITLE
Add a theme option for a second text color for hover and select state

### ISSUE THREAD

**Issue by hc1abearden** [naisutech/react-tree#10]
I would have found it helpful to have a second text color option for on-hover / select state. If I have a highlight color added, I would like to have the text color change, wherever this highlight color appears. Thanks

**Comment by ortonomy** [comment]
Fork, and open a PR? This is a good enhancement. I just don't have time right now.

**Comment by ortonomy** [comment]
@hc1abearden -- Sorry for the delay in this, I guess you're not using this any more, but for anyone else who also wants this, I've rewritten the theming API to use a more logical set of properties: https://naisutech.github.io/react-tree/?path=/story/react-tree--with-controls

**Comment by hc1abearden** [comment]
> @hc1abearden -- Sorry for the delay in this, I guess you're not using this any more, but for anyone else who also wants this, I've rewritten the theming API to use a more logical set of properties: https://naisutech.github.io/react-tree/?path=/story/react-tree--with-controls

Thanks for the update @ortonomy
