### ISSUE TITLE
Invalid hook call when using in class component

### ISSUE THREAD

**Issue by Telanore** [naisutech/react-tree#11]
I want to use this in my class component, which is a side bar, but whenever I add it to the render function, it causes an "Invalid hook call" error further up in my class. I'm not that experienced with React, but it's as if it thinks my entire class is a functional component when I add your Tree component.

It works as expected when I remove `<Tree nodes={this.state.root} size="narrow" />` from the render function.

My sidebar class:

````
import React, { Component } from 'react';
import FileModel from '../FileModel';
import Tree from '@naisutech/react-tree'

export class Sidebar extends Component {
  constructor (props) {
    super(props);
    this.state = {
      root: {}
    }
  }

  componentDidMount() {
    this.getFolders();
  }

  async getFolders() {
    let resp = await fetch('/api/Folder');
    let data = await resp.json();
    let root = new FileModel(data);
    this.setState({ root: root }); //Error here
  }

  render() {
    return (
      <div className="sidebar">
        <Tree nodes={this.state.root} size="narrow" />
      </div>
    );
  }
}

**Comment by ortonomy** [comment]
What version of `react-dom` do you babe in your `package.json`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ortonomy** [comment]
Minimal repro using react `16.12` shows working fine in class component: 

https://codesandbox.io/s/issue-11-use-in-class-ik44y?file=/src/MyClassComponent.js

Closing for now.
