### ISSUE TITLE
Change or add SVG Icons

### ISSUE THREAD

**Issue by ThisIsMrAli** [naisutech/react-tree#12]
Hi There,
Recently i used your project and I love it very much. Would you please help me how can add or change SVG icons you used? i like to customize it to be like the attached image.
![image](https://user-images.githubusercontent.com/31847887/83126567-3c25eb00-a0ee-11ea-994b-fb44294338fc.png)

**Comment by ortonomy** [comment]
@ThisIsMrAli  -- please note new release `0.4.2` now can hide / change icons:

https://www.npmjs.com/package/@naisutech/react-tree
