### ISSUE TITLE
Prop to specify no SVG Icon

### ISSUE THREAD

**Issue by noahking27** [naisutech/react-tree#16]
Looking for a way to specify no svg file icon or ability to change it. I don't see currently an easy way to hide it.

**Comment by ortonomy** [comment]
similar to #12 -- will add soon, unless you want to open a PR @noahking27 ?

**Comment by ortonomy** [comment]
@noahking27 -- please note new release `0.4.2` now can hide / change icons:

https://www.npmjs.com/package/@naisutech/react-tree
