### ISSUE TITLE
How Can I move Arrow icon to right hand side

### ISSUE THREAD

**Issue by pasindu-nawodya** [naisutech/react-tree#19]
I'm new to react. I want to use this for my campus project. But in requirement it says arrow should be in right hand side. How can I move Arrow icon to right hand side? And also I need to disable arrow icon in last children node. Thank you!
@ortonomy

**Comment by ortonomy** [comment]
@pasindu-nawodya -- I'm not going to have time to help you with this over the next few weeks. Please go ahead and try to use it, you could fork the code, or copy it into your own project as a component and modify from there?

You can start here: https://github.com/naisutech/react-tree/blob/master/src/Tree/NodeElement.js#L56, which is where the icon is rendered.

**Comment by Litaash** [comment]
Hi, how can I define in tree child elements with custom class?

for example: 
<div class="thee tree-one has-children">Items<div/>
<div class="thee tree-two has-children">Items 2<div/>
<div class="thee tree-three without-children">Item<div/>

**Comment by ortonomy** [comment]
@Litaash -- I'm not really sure what this means and please refrain from hijacking someone else's issue. Open a new one with your question and preferably some screenshots or diagrams / better description of what you're trying to achieve.
