### ISSUE TITLE
Is there API to expand all elements ?

### ISSUE THREAD

**Issue by maifeeulasad** [naisutech/react-tree#20]
I looked for this into documentation section, couldn't find any. Maybe this will be a really cool feature/enhancement.

**Comment by mtucciarone** [comment]
+1

**Comment by ortonomy** [comment]
Sorry I've not been very responsive. Busy here. I'll take a look at the PR.

**Comment by ortonomy** [comment]
go for it

**Comment by ortonomy** [comment]
@mtucciarone and @maifeeulasad -- this is now possible with the release of v2: https://github.com/naisutech/react-tree/releases/tag/2.0.0

See demo: https://naisutech.github.io/react-tree/?path=/story/react-tree--with-controls
