### ISSUE TITLE
how to to override ride expand and transform styles 

### ISSUE THREAD

**Issue by Abhijeet501** [naisutech/react-tree#25]
So basically I am trying to remove the transformed icon and  add a new icon when the node is clicked 
![Capture](https://user-images.githubusercontent.com/48730739/103357590-8e166100-4a81-11eb-803c-ddd596c682bb.JPG)
Instead of rotating the folder to 90 degree after clicking the node i want to replace it with open folder image. thank you for any suggestions

**Comment by Abhijeet501** [comment]
Instead of rotating the folder to 90 degree after clicking the node i want to replace it with open folder image. thank you for any suggestions

**Comment by ortonomy** [comment]
not possible at the moment,  but I'll add the possibilty

**Comment by Abhijeet501** [comment]
Thank you Ortonomy. I appreciate it.

**Comment by ortonomy** [comment]
You can now use a custom `IconRenderer`, `NodeRenderer`, and `LeafRenderer` to override contents that won't be impacted by default transforms!

https://naisutech.github.io/react-tree/
