### ISSUE TITLE
Move onto React Class Component and typescript

### ISSUE THREAD

**Issue by maifeeulasad** [naisutech/react-tree#28]
For better manageability move onto React Class Component and typescript for type-checking.

**Comment by ortonomy** [comment]
Two different issues, should be separate. 

But to address:

1. > For better manageability move onto React Class Component

Not sure what this means, but no, this will not happen. React Class components are legacy. Functional components are preferred in almost all cases in modern React.

2. Personally, I'm not a fan of typescript, so no.
