### ISSUE TITLE
Could not find a declaration file

### ISSUE THREAD

**Issue by guopuu** [naisutech/react-tree#29]
run npm install ...

import Tree from '@naisutech/react-tree'

then error :

Could not find a declaration file for module '@naisutech/react-tree'. 'd:/myWork/my_tcb_client/TCBWebClient/node_modules/@naisutech/react-tree/build/Tree.js' implicitly has an 'any' type.
  Try `npm install @types/naisutech__react-tree` if it exists or add a new declaration (.d.ts) file containing `declare module '@naisutech/react-tree';`ts(7016)

**Comment by ortonomy** [comment]
Are you using typescript? This library doesn't support or use Typescript. feel free to write your own types.
