### ISSUE TITLE
Add a tooltip to the node elements

### ISSUE THREAD

**Issue by lcaouen** [naisutech/react-tree#31]
When the text is too long the text is truncated and you display an ellipsis.
That's perfect however, it would be great to have the possibility to see all the text when moving the mouse over it.
The NodeText is a span, addind a title with the text would solve the problem.
![Capture](https://user-images.githubusercontent.com/3267663/107144539-0bb07500-693c-11eb-85c2-fee08ed8a368.PNG)
![Capture2](https://user-images.githubusercontent.com/3267663/107144556-300c5180-693c-11eb-82ae-d06868282b27.PNG)

**Comment by ortonomy** [comment]
This is an easy fix. I agree.

**Comment by ortonomy** [comment]
Fixed in v2! See :https://github.com/naisutech/react-tree/releases/tag/2.0.0

And demo: https://naisutech.github.io/react-tree/?path=/story/react-tree--truncated-long-labels

**Comment by lcaouen** [comment]
Sorry for this late answer, I just didn't have the time to test it before.
It works fine. Thanks for the change !
