### ISSUE TITLE
Introduce `selected` prop

### ISSUE THREAD

**Issue by pablopunk** [naisutech/react-tree#32]
Hi there! I couldn't find any request for this so I'll explain what I would like to see in this awesome repo 😊

```jsx
<Tree
  nodes={treeData}
  selected={treeData[0].id} // I'm forcing the tree to select the first node
/>
```

Basically, introduce a prop to allow the selection of elements without interacting with the Tree UI.

### Example use-case

Let's say I'm using `<Tree />` on the left of the screen to render a list of HTML tags that I'm actually rendering to the DOM on the right of the screen. When I click on an HTML element (on the right) I want the tree to show that tag as selected.

Seeing how the `selected` prop is being passed down internally, maybe it's easier to pass the actual node instead of the id:

```jsx
<Tree selected={treeData[0]} />
```

**Comment by ortonomy** [comment]
Hi @pablopunk -- I've reviewed this, and I think it's fine if we introduced an API to include a selected value into the data list (this would be the responsibilitty of the data provider to indicate to the component which node is selected)

We can introduce the relevant stylings based off this attribute in the node entry in the list, and make it styleable via the theme.

Feel free to open a PR to make this happen!

**Comment by ortonomy** [comment]
Let me know if you want help / pointers where to start making changes.

**Comment by ortonomy** [comment]
Hi @pablopunk -- v2 is now released! 

I think you'll find what you're looking for with the introduction of render props: https://github.com/naisutech/react-tree#programatically-selecting-multiple-elements
