### ISSUE TITLE
Tree not re rendering after button click and updating data?

### ISSUE THREAD

**Issue by rushic24** [naisutech/react-tree#34]

**Comment by rushic24** [comment]
`onMck = () => {
        this.setState({data :[{
            "id": 87654325,
            "label": "My file9",
            "parentId": 56789012
        }]});
        console.log(this.state.data);
        // document.getElementById("mtree").innerHTML = createTree(data)
    };`

`<button onClick={this.onMck}/>`

` <Tree nodes={this.state.data} onSelect={this.onSelect} theme={'my-theme'} customTheme={myTheme}/>`

**Comment by ortonomy** [comment]
is `this.state.data` empty before your button press?

**Comment by ortonomy** [comment]
this should be fixed now in v2. Let me know if it's still a problem
