### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by ortonomy** [naisutech/react-tree#44]
We need to remove flow and rewrite the lib to use typescript

**Comment by ortonomy** [comment]
closed by https://github.com/naisutech/react-tree/releases/tag/2.0.0

**Comment by AlexLeung** [comment]
I don't think the type definitions are being published

**Comment by AlexLeung** [comment]
![image](https://user-images.githubusercontent.com/5025138/126881993-649f0563-aea5-4bbf-9438-41b8ce0dbad2.png)

you need to include the d.ts files in the dist folder

**Comment by ortonomy** [comment]
Ah, thanks @AlexLeung - I thought I'd configured it to make sure it was in the bundle. Let me verify and fix.

**Comment by ortonomy** [comment]
Finally fixed a bug with mix of styled-component + framer motion passing down props they shouldn't + published version with the correct type definitions exported. All seems to be working.
