### ISSUE TITLE
Only one leaf node opened

### ISSUE THREAD

**Issue by qtarant** [naisutech/react-tree#45]
Hello. Firstly, thanks for this very good component. Very practical and customizable.
I have a doubt, that I can not find how to do if it is posible:
I would like to have one leaf node opened and only one. So when I click on one leaf node, I would like to have all of opened nodes to be closed.
How can I get this behavior?
Thanks in advance.

**Comment by ortonomy** [comment]
Hi, @qtarant -- can you try to explain things a bit more -- do you mean you want to have a single leaf node open, even if there are multiple leaves in the folder?
