### ISSUE TITLE
Remove Empty node shown at the bottom of the each level

### ISSUE THREAD

**Issue by DimuthRuwantha** [naisutech/react-tree#5]
There is a leaf shown at each level showing [empty]
it should be removed
![image](https://user-images.githubusercontent.com/25617739/75311965-7b8a3480-587e-11ea-8e1e-7dadddbb3fa7.png)

**Comment by ortonomy** [comment]
Hi, @DimuthRuwantha! thanks for contributing -- This is by design. It should not be changed. Empty leaves are only shown for empty folders.

If you wish to enable an API that disables empty leaves, please open a PR with the changes and I will review.

**Comment by ortonomy** [comment]
@DimuthRuwantha -- the new version `v0.2.1` has the empty file indicators off by default - but you can re-enable them again with a prop.
