### ISSUE TITLE
[Icons] Pass node/leaf data to `IconRenderer`

### ISSUE THREAD

**Issue by blindpirate** [naisutech/react-tree#51]
Thanks for creating the awesome project!

Currently `IconRenderer` is passed with a string parameter `node`/`leaf`, but no node name. My use case is to render a file tree, which I hope to render different type of node with different icon, e.g. `.txt` file with text icon, `.mp4` file with media player icon, etc.

I would expect `IconRenderer` to pass `{label:"node", name: "file.txt"}` or something similar.

**Comment by ortonomy** [comment]
Hi, @blindpirate -- thanks for the request. I'll response shortly.

**Comment by ortonomy** [comment]
Hi, @blindpirate -- I've had a chance to look at what you're suggesting, and the approach I would take here, I think, is to just pass the current node/leaf data object the icon renderer so you can do your own conditional rendering based on whatever tests/values you want. 

I can get to this, but it's not likely to be soon. 

If you want, you could modify the code and open a PR? I'd be happy to merge this change into the code base.

**Comment by Ekk9** [comment]
Currently I'm evaluating different Tree renderers and like your project a lot. Unfortunately this missing feature might make it not usable for us. Is this slated to get added anytime soon?

**Comment by ortonomy** [comment]
@Ekk9 -- i can look to add it in the next few weeks.

**Comment by yokeshwar93** [comment]
@ortonomy is there any update on when we can expect this Thanks

**Comment by ortonomy** [comment]
@yokeshwar93  @Ekk9  @blindpirate  

Added support in `v2.1.0`
