### ISSUE TITLE
[BUG] onSelect is being triggered when clicking on any place 

### ISSUE THREAD

**Issue by mizo121** [naisutech/react-tree#55]
Hello
There are two issues related to using one Tree instance or multiple instances.
If we are using for example two Tree instances with onSelect for each one of them
Both are triggered on selecting any node in any one of both Trees and that is completely wrong and gets me invalid values.

Note: This error wasn't there before version 2.0.0 and i cannot downgrade because of not supporting typescript.

**Comment by ortonomy** [comment]
https://stackblitz.com/edit/react-ts-fuzxob

i can't reproduce what you're describing. please reproduce and demo to me and I will re-open and fix.

**Comment by dontpanic92** [comment]
@ortonomy The demo you provided exactly reproduced the issue:

![react-tree](https://user-images.githubusercontent.com/1056013/168579507-48308d73-428a-4ea7-937b-f924a0947bae.gif)

I'm using Chrome 101 and Firefox 100. It can be reproduced on both browsers.
