### ISSUE TITLE
[Icons] Pass isOpen data to IconRenderer

### ISSUE THREAD

**Issue by Minobi** [naisutech/react-tree#60]
`IconRenderer` function receive `node/leaf` and `data` parameters, but we don't know current state of the node inside this function. I want to render different icons for open and closed nodes. Maybe add third parameter `isOpen` to `IconRenderer` function or inside `data` parameter?

**Comment by ortonomy** [comment]
will be in v3

**Comment by ortonomy** [comment]
is in v2, and closed by #72
