### ISSUE TITLE
Several instances of styled-components

### ISSUE THREAD

**Issue by cdolek** [naisutech/react-tree#61]
Fresh create-react-app sourced application, whenever I include the <Tree /> component, I get the following warning in console:

```
styled-components.esm.js:1 It looks like there are several instances of 'styled-components' initialized in
this application. This may cause dynamic styles to not render properly, errors during the rehydration
process, a missing theme prop, and  makes your application bigger without good reason.

See https://s-c.sh/2BAXzed for more info.

```

same thing happened with styled components `v5.3.3` and `v5.3.5`

**Comment by ortonomy** [comment]
Hmmm, this might be challenging to fix as `react-tree` depends on styled components. I guess I could put it as a peer dependency

**Comment by ortonomy** [comment]
This is because styled-components was not a peer dependency. Have moved it @cdolek

**Comment by cdolek** [comment]
that should work...
