### ISSUE TITLE
is there a way to configure Tree to expand all nodes?

### ISSUE THREAD

**Issue by cevaris** [naisutech/react-tree#64]
What is the best way to render all nodes in open state by default? 

I was able to get the following working in Typescript, but seemingly not the best approach... Is the following the intended way?
```
            <Tree nodes={nodes} theme="light">
                {(controls) => {
                    if (controls.toggleOpenCloseAllNodes && controls.openNodeIds?.length == 0) {
                        controls.toggleOpenCloseAllNodes();
                    }
                    return <></>
                }}
            </Tree>
```

Ideally, there would be some Tree prop that we can easily pass in the openNodeIds state.., or perhaps a `openAllNodes={boolean}` prop?

```
            <Tree nodes={nodes} theme="light" openNodeIds={[1, 2]}>
            </Tree>
            
            <Tree nodes={nodes} theme="light" openAllNodes>
            </Tree>
```

Thoughts?

**Comment by ortonomy** [comment]
v3 will provide an imperative api using a hook `useReactTreeApi()` which will allow for open, close, select, deselect methods

**Comment by ortonomy** [comment]
@cevaris  - two ways now v3 has been published:

**method 1**

- provide ALL node IDs to `selectedNodes` or `defaultSelectedNodes`

**method 2**

- use the imperative API exposed by the hook

**Comment by cevaris** [comment]
Sounds good. Thanks!
