### ISSUE TITLE
callbacks causing rendering problems

### ISSUE THREAD

**Issue by peeveen** [naisutech/react-tree#68]
Hi,

The onSelect and onOpenClose callbacks are currently called from within a setState() hook.
If I have some code in my callback function to modify my app state (which, in turn, will cause another component to re-render), I get the dreaded "cannot update a component while rendering a different component" error in the console.
I've fixed it for now by removing the callbacks, and instead, just having this in the main component body, but there may be a better solution:

![image](https://user-images.githubusercontent.com/23334330/177577267-1e3aa3cd-0b0a-4f55-91f4-a91c2d302f23.png)

**Comment by ortonomy** [comment]
This is for sure a better solution, and I saw your PR. Made a comment

**Comment by ortonomy** [comment]
I've published v3 which removes all the calls in memos, and take into account your PR, but doesn't use the same approach, closed.
