### ISSUE TITLE
Tree Component doesnt re render

### ISSUE THREAD

**Issue by brunoqs** [naisutech/react-tree#7]
The Tree component does not re render when the state of the parent component changes

**Comment by ortonomy** [comment]
Hi @brunoqs -- can you show me a demo of what the problem is and I'll look at it further.

The way react works, a component will only re-render if the props it depends on change. If the data you're putting into the tree doesn't change, then the component will not re-render.

**Comment by brunoqs** [comment]
Hi @ortonomy I created the structure to render in the tree, and when i click on a parent node, I bring the child nodes and update the object node, but the tree does not render again

**Comment by ortonomy** [comment]
@brunoqs -- I'll write some jest tests this weekend and fix it if I can reproduce.

**Comment by ortonomy** [comment]
Thanks for your patience @brunoqs  -- I've released a [new version](https://github.com/naisutech/react-tree/releases/tag/v0.2.1) and published to NPM.

Please note readme changes with a few API changes...
