### ISSUE TITLE
Controlled mode not working

### ISSUE THREAD

**Issue by nz303** [naisutech/react-tree#76]
Hello,

it seems like controlled mode is not working.

Even if openNodes and selectedNodes are set without defaultOpenNodes and defaultSelectedNodes the tree still collapses and selects nodes on click.

`<ReactTree openNodes={[]} selectedNodes={[]} nodes={nodes} />;`

Demo:
https://codesandbox.io/s/infallible-moser-8uly0o?file=/src/App.js

Can you provide an example for controlled mode?

Thanks a lot :)

**Comment by ortonomy** [comment]
@nz303 -- thanks a lot for testing and pointing out bug! fixed by #77

**Comment by ortonomy** [comment]
new version published as `v3.0.1`. Please try that

**Comment by nz303** [comment]
ty - will try :) Also thank you for updating the docu.
