### ISSUE TITLE
[help needed] Invalid DOM property and validateDOMNesting(...) Warnings.

### ISSUE THREAD

**Issue by alexbashkov** [naisutech/react-tree#78]
Hello,

I'm having issues with the latest release (v3.0.1). It was working fine with the older v2.0, but now I get 2 warnings in the console:

1. `Warning: Invalid DOM property `Icon`. Did you mean `icon`?`
2. `Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>`

Also, got an import error with v3.0.1, so I had to do the following (despite what documentation is saying):
`import` { ReactTree } from "@naisutech/react-tree";`

I would appreciate any help in resolving these issues, or if this needs to be addressed with a new PR

**Comment by alexbashkov** [comment]
Hi, any news on the issue of nesting custom components in a leaf? thanks

**Comment by ortonomy** [comment]
hi @alexbashkov  - I've fixed some issues:

> Warning: Invalid DOM property Icon. Did you mean icon?
> Also, got an import error with v3.0.1

however:

> Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>

You'll need to give me a repro of this on codesandbox or stackblitz because I'm not sure what you're doing to cause this. I've added a custom render for node and icons to the docs for testing and I can't repro
