### ISSUE TITLE
multiSelect doesn't work in controlled mode

### ISSUE THREAD

**Issue by alexbashkov** [naisutech/react-tree#87]
Using the latest build (v3.1.0 which I was eager to install because it would fix some major issues for me). So, that version now introduces a singleSlect node option by default. Using the multiSelect={true} flag does not work in controlled state for me.

The callback onToggleOpenNodes always returns an array of 1 item that was lastly selected. Let me know if I am doing something wrong or please fix this.

**Comment by ortonomy** [comment]
@alexbashkov  - onToggleOpenNodes is only going to give you a list of the last clicked node. It doesn't tell you what's selected...
