### ISSUE TITLE
Duplicate items for same parent

### ISSUE THREAD

**Issue by ravic0** [naisutech/react-tree#9]
Hi, the library works as needed for me but there's an issue when multiple children with same parent gets created:

To reproduce, change parent id of last object with label 'Node' to  1234 (The root parent id)
https://codesandbox.io/s/naisu-techreact-tree-demo-p42lv

**Comment by ortonomy** [comment]
OK, I seem to be able to verify this. It duplicates the children of a parent. I will test and fix.

**Comment by ortonomy** [comment]
Thanks for your patience @ravic0 -- I've released a [new version](https://github.com/naisutech/react-tree/releases/tag/v0.2.1) a new version and published to NPM.

Please note readme changes with a few API changes...
